import { StitchesRegistry } from "@/styles/global";
import { getCssText } from "@pedroandrad1/react";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const roboto = Roboto({ subsets: ["latin"], weight: ['400','700', '900'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StitchesRegistry>{children}</StitchesRegistry>
      </body>
    </html>
  );
}
